package com.github.idea.arthas.plugin.ui;

import com.github.idea.arthas.plugin.utils.ActionLinkUtils;
import com.github.idea.arthas.plugin.utils.ClipboardUtils;
import com.github.idea.arthas.plugin.utils.NotifyUtils;
import com.github.idea.arthas.plugin.utils.StringUtils;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.WindowManager;
import com.intellij.ui.components.ActionLink;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class ArthasClassLoaderLoadClassCommandDialog extends JDialog {
    private JPanel contentPane;
    private JTextField classloaderHashValueTextField;
    private JButton classLoaderHashValueCommandButton;
    private JButton scCommandButton;
    private JTextField scTextField;
    private JButton loadClassCommandButton;
    private JTextField classloaderLoadTextField;
    private JLabel classloaderListLabel;
    private ActionLink helpLink;
    private ActionLink scLink;
    private JButton closeButton;

    private Project project;
    private String className;

    public ArthasClassLoaderLoadClassCommandDialog(Project project, String className) {
        this.project = project;
        this.className = className;
        $$$setupUI$$$();
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(closeButton);


        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        init();
    }

    private void init() {
        String classLoaderCommand = String.join(" ", "classloader --load", className);
        classloaderLoadTextField.setText(classLoaderCommand);

        String scCommand = String.join(" ", "sc -d", className);
        scTextField.setText(scCommand);

        scCommandButton.addActionListener(e -> {
            String text = scTextField.getText();
            ClipboardUtils.setClipboardString(text);
            NotifyUtils.notifyMessage(project, "search all the classes loaded by jvm");
        });

        loadClassCommandButton.addActionListener(e -> {
            String classloaderHashValue = classloaderHashValueTextField.getText();
            if (StringUtils.isBlank(classloaderHashValue)) {
                NotifyUtils.notifyMessage(project, " use classLoader to load class, won't work without -c specified");
                return;
            }
            //classloader --load demo.MathGame
            String loadTextFieldText = classloaderLoadTextField.getText();
            String loadClassCommand = String.join(" ", loadTextFieldText, "-c", classloaderHashValue);
            ClipboardUtils.setClipboardString(loadClassCommand);
            NotifyUtils.notifyMessage(project, "if load class success, at once search all the classes loaded by jvm");
        });
        classLoaderHashValueCommandButton.addActionListener(e -> {
            ClipboardUtils.setClipboardString("classloader -l");
            NotifyUtils.notifyMessage(project, " display list info by classloader instance,select one hava value to load current class");
        });
        closeButton.addActionListener(e -> {
            onCancel();
        });

    }

    private void onOK() {
        // add your code here
        dispose();
    }

    private void onCancel() {
        // add your code here if necessary
        dispose();
    }

    /**
     * 打开窗口
     */
    public void open(String title) {
        setTitle(title);
        pack();
        //两个屏幕处理出现问题，跳到主屏幕去了
        setLocationRelativeTo(WindowManager.getInstance().getFrame(this.project));
        setVisible(true);

    }

    private void createUIComponents() {
        helpLink = ActionLinkUtils.newActionLink("https://arthas.aliyun.com/doc/classloader");
        scLink = ActionLinkUtils.newActionLink("https://arthas.aliyun.com/doc/sc");
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(6, 3, new Insets(10, 10, 10, 10), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("classloader --load");
        contentPane.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        classloaderListLabel = new JLabel();
        classloaderListLabel.setText("-c classloader");
        classloaderListLabel.setToolTipText("获取classloader hash (classloader -l)");
        contentPane.add(classloaderListLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        classloaderHashValueTextField = new JTextField();
        contentPane.add(classloaderHashValueTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        classLoaderHashValueCommandButton = new JButton();
        classLoaderHashValueCommandButton.setText("copy command");
        contentPane.add(classLoaderHashValueCommandButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scCommandButton = new JButton();
        scCommandButton.setText("copy command");
        contentPane.add(scCommandButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scLink.setText("search class in jvm");
        contentPane.add(scLink, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scTextField = new JTextField();
        contentPane.add(scTextField, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        loadClassCommandButton = new JButton();
        loadClassCommandButton.setText("copy command");
        contentPane.add(loadClassCommandButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        classloaderLoadTextField = new JTextField();
        contentPane.add(classloaderLoadTextField, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("load class commad use current classloader hash value");
        label2.setToolTipText("使用当前hash值加载");
        contentPane.add(label2, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        helpLink.setText("help");
        contentPane.add(helpLink, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        closeButton = new JButton();
        closeButton.setText("关闭");
        contentPane.add(closeButton, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
