package com.github.idea.arthas.plugin.ui;

import com.github.idea.arthas.plugin.utils.ActionLinkUtils;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.WindowManager;
import com.intellij.ui.components.ActionLink;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 * arthas 特殊用法
 *
 * @author 汪小哥
 * @date 22-12-2019
 */
public class ArthasSpecialDialog extends JDialog {
    private ActionLink specialOgnlActionLink;
    private ActionLink ttGetSpringContextActionLink;
    private ActionLink errorFilterActionLink;
    private ActionLink dubboArthasActionLink;
    private ActionLink redefineLinLabel;
    private JPanel contentPane;
    private ActionLink ognlUseActionLink;
    private ActionLink userCase;
    private ActionLink tt;
    private ActionLink conditionArthas;
    private ActionLink watchSpringContext;
    private ActionLink asyncExample;
    private ActionLink arthasBestUnderStand;
    private ActionLink arthasJprofileLink;
    private ActionLink springAopTarget;
    private ActionLink arthasVersionLink;

    private Project project;

    public ArthasSpecialDialog(Project project) {
        this.project = project;
        $$$setupUI$$$();
        setContentPane(this.contentPane);
        setModal(false);

        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(e -> onCancel(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);


    }

    /**
     * 关闭
     */
    private void onCancel() {
        dispose();
    }

    private void createUIComponents() {
        specialOgnlActionLink = ActionLinkUtils.newActionLink("https://github.com/alibaba/arthas/issues/71");
        ttGetSpringContextActionLink = ActionLinkUtils.newActionLink("https://github.com/alibaba/arthas/issues/482");
        errorFilterActionLink = ActionLinkUtils.newActionLink("https://github.com/alibaba/arthas/issues/429");
        dubboArthasActionLink = ActionLinkUtils.newActionLink("https://hengyunabc.github.io/dubbo-meet-arthas/");
        redefineLinLabel = ActionLinkUtils.newActionLink("https://hengyunabc.github.io/arthas-online-hotswap/");
        ognlUseActionLink = ActionLinkUtils.newActionLink("https://blog.csdn.net/u010634066/article/details/101013479");
        userCase = ActionLinkUtils.newActionLink("https://github.com/alibaba/arthas/issues?utf8=%E2%9C%93&q=+is%3Aissue+label%3Auser-case+");
        conditionArthas = ActionLinkUtils.newActionLink("https://github.com/WangJi92/arthas-idea-plugin/issues/6");
        tt = ActionLinkUtils.newActionLink("https://github.com/WangJi92/arthas-idea-plugin/issues/4");
        watchSpringContext = ActionLinkUtils.newActionLink("https://github.com/WangJi92/arthas-idea-plugin/issues/5");
        asyncExample = ActionLinkUtils.newActionLink("https://www.cnblogs.com/leihuazhe/p/11630466.html");
        arthasBestUnderStand = ActionLinkUtils.newActionLink("https://wangji.blog.csdn.net/article/details/106964278");
        arthasJprofileLink = ActionLinkUtils.newActionLink("https://github.com/alibaba/arthas/issues/1416");
        springAopTarget = ActionLinkUtils.newActionLink("https://github.com/alibaba/arthas/issues/1424");
        arthasVersionLink = ActionLinkUtils.newActionLink("https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzkxNDI0ODE0NQ==&action=getalbum&album_id=1896318852766973955&scene=173&from_msgid=2247484030&from_itemidx=1&count=3&nolastread=1#wechat_redirect");

    }

    /**
     * 打开窗口
     */
    public void open() {
        setTitle("arthas special use");
        pack();
        setMinimumSize(new Dimension(378, 242));
        //两个屏幕处理出现问题，跳到主屏幕去了 https://blog.csdn.net/weixin_33919941/article/details/88129513
        setLocationRelativeTo(WindowManager.getInstance().getFrame(this.project));
        setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(16, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("arthas 特殊用法");
        contentPane.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        specialOgnlActionLink.setText("special ognl");
        contentPane.add(specialOgnlActionLink, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ttGetSpringContextActionLink.setText("tt get spring context");
        contentPane.add(ttGetSpringContextActionLink, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        errorFilterActionLink.setText("get ERROR Filter");
        contentPane.add(errorFilterActionLink, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dubboArthasActionLink.setText("Dubbo 遇上arthas");
        contentPane.add(dubboArthasActionLink, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        redefineLinLabel.setText("jad/mc/redefine线上热更新一条龙");
        contentPane.add(redefineLinLabel, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ognlUseActionLink.setText("ognl使用姿势");
        contentPane.add(ognlUseActionLink, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        userCase.setText("arthas user case");
        contentPane.add(userCase, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tt.setText("TimeTunnel Tt 时间隧道");
        contentPane.add(tt, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        conditionArthas.setText("条件表达式过滤常见使用+异步任务");
        contentPane.add(conditionArthas, new GridConstraints(10, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        watchSpringContext.setText("Watch Spring context invoke method field");
        contentPane.add(watchSpringContext, new GridConstraints(11, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        asyncExample.setText("使用Async-profiler 对程序性能优化实战");
        contentPane.add(asyncExample, new GridConstraints(12, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        arthasBestUnderStand.setText("arthas 入门最佳实践");
        contentPane.add(arthasBestUnderStand, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        arthasJprofileLink.setText("使用arthas+jprofiler做复杂链路分析");
        contentPane.add(arthasJprofileLink, new GridConstraints(13, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        springAopTarget.setText("arthas 获取spring被代理的目标对象");
        contentPane.add(springAopTarget, new GridConstraints(14, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        arthasVersionLink.setText("arthas 版本升级博客大全");
        contentPane.add(arthasVersionLink, new GridConstraints(15, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
