package com.github.idea.arthas.plugin.ui;

import com.github.idea.arthas.plugin.constants.ArthasCommandConstants;
import com.github.idea.arthas.plugin.utils.ActionLinkUtils;
import com.github.idea.arthas.plugin.utils.PropertiesComponentUtils;
import com.github.idea.arthas.plugin.utils.StringUtils;
import com.intellij.ide.util.PropertiesComponent;
import com.intellij.openapi.options.Configurable;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.ui.components.ActionLink;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/**
 * 设置界面处理
 * {@literal https://cloud.tencent.com/developer/article/1348741 }
 * {@literal https://www.jetbrains.org/intellij/sdk/docs/basics/persisting_state_of_components.html }
 * {@literal http://corochann.com/intellij-plugin-development-introduction-persiststatecomponent-903.html }
 * {@literal https://blog.xiaohansong.com/idea-plugin-development.html}
 * {@literal http://www.dcalabresi.com/blog/java/spring-context-static-class/}
 *
 * @author 汪小哥
 * @date 22-12-2019
 */
@Deprecated
public class SettingDialog implements Configurable {
    private JTextField springContextStaticOgnlExpressionTextFiled;
    private JPanel contentPane;
    private ActionLink linkLable;

    public SettingDialog() {
        $$$setupUI$$$();
        initData();
    }

    private void initData() {
        PropertiesComponent propertiesComponent = PropertiesComponent.getInstance();
        String oldspringContextEx = propertiesComponent.getValue(ArthasCommandConstants.PRO_PREFIX + ArthasCommandConstants.SPRING_CONTEXT_STATIC_OGNL_EXPRESSION);
        if (StringUtils.isBlank(oldspringContextEx)) {
            oldspringContextEx = ArthasCommandConstants.DEFAULT_SPRING_CONTEXT_SETTING;
            PropertiesComponentUtils.setValue(ArthasCommandConstants.SPRING_CONTEXT_STATIC_OGNL_EXPRESSION, oldspringContextEx);

        }
        springContextStaticOgnlExpressionTextFiled.setText(oldspringContextEx);

    }

    @Nls(capitalization = Nls.Capitalization.Title)
    @Override
    public String getDisplayName() {
        return "ArthasIdeaPlugin";
    }

    @Nullable
    @Override
    public JComponent createComponent() {
        return contentPane;
    }

    @Override
    public boolean isModified() {
        String springContextStaticOgnlExpressionText = springContextStaticOgnlExpressionTextFiled.getText();
        return !Objects.equals(springContextStaticOgnlExpressionText, PropertiesComponentUtils.getValue(ArthasCommandConstants.SPRING_CONTEXT_STATIC_OGNL_EXPRESSION));
    }

    @Override
    public void apply() throws ConfigurationException {
        String springContextStaticOgnlExpressionText = springContextStaticOgnlExpressionTextFiled.getText();
        PropertiesComponentUtils.setValue(ArthasCommandConstants.SPRING_CONTEXT_STATIC_OGNL_EXPRESSION, springContextStaticOgnlExpressionText);


    }

    @Override
    public void reset() {

    }

    private void createUIComponents() {
        /**
         * 处理访问链接 参考 {@literal https://github.com/YiiGuxing/TranslationPlugin}
         */
        linkLable = ActionLinkUtils.newActionLink("http://www.dcalabresi.com/blog/java/spring-context-static-class/");
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 2, new Insets(5, 10, 10, 5), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(2);
        label1.setHorizontalTextPosition(0);
        label1.setText("variable(#springContext)");
        contentPane.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(157, 72), null, 0, false));
        linkLable.setText("Spring Context eg:@applicationContextProvider@context");
        contentPane.add(linkLable, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(370, 72), null, 0, false));
        springContextStaticOgnlExpressionTextFiled = new JTextField();
        springContextStaticOgnlExpressionTextFiled.setText("");
        springContextStaticOgnlExpressionTextFiled.setToolTipText("spring context  static ognl expression");
        contentPane.add(springContextStaticOgnlExpressionTextFiled, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(180, 32), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(2);
        label2.setHorizontalTextPosition(2);
        label2.setText("ognl expression");
        label2.setToolTipText("spring context ognl expression");
        contentPane.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(157, 32), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("变量: #springContext=@applicationContextProvider@context");
        contentPane.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(157, 16), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("调用方法数据: ,#springContext.getBean(\"controller\").test(\"param\")");
        contentPane.add(label4, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
